from typing import Annotated
from fastapi import Depends
from limiter.limiter_rules import (
    LIMIT_10_PER_5MIN, 
    LIMIT_10_PER_MINUTE,
    LIMIT_3_PER_MINUTE,
    LIMIT_5_PER_MINUTE,
    LIMIT_15_PER_MINUTE,
    LIMIT_20_PER_MINUTE,
    LIMIT_3_PER_2MIN,
    LIMIT_10_PER_2MIN,
    LIMIT_5_PER_3MIN
)


LIMIT_3_PER_MINUTE_DEPENDENCY = Depends(LIMIT_3_PER_MINUTE)
LIMIT_5_PER_MINUTE_DEPENDENCY = Depends(LIMIT_5_PER_MINUTE)
LIMIT_10_PER_MINUTE_DEPENDENCY = Depends(LIMIT_10_PER_MINUTE)
LIMIT_15_PER_MINUTE_DEPENDENCY = Depends(LIMIT_15_PER_MINUTE)
LIMIT_20_PER_MINUTE_DEPENDENCY = Depends(LIMIT_20_PER_MINUTE)
LIMIT_3_PER_2MIN_DEPENDENCY = Depends(LIMIT_3_PER_2MIN)
LIMIT_10_PER_2MIN_DEPENDENCY = Depends(LIMIT_10_PER_2MIN)
LIMIT_5_PER_3MIN_DEPENDENCY = Depends(LIMIT_5_PER_3MIN)
LIMIT_10_PER_5MIN_DEPENDENCY = Depends(LIMIT_10_PER_5MIN)
